# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'decToBin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(553, 226)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.convertButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.convert())
        self.convertButton.setGeometry(QtCore.QRect(220, 70, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(14)
        font.setItalic(True)
        self.convertButton.setFont(font)
        self.convertButton.setObjectName("convertButton")
        self.input_2 = QtWidgets.QLabel(self.centralwidget)
        self.input_2.setGeometry(QtCore.QRect(20, 10, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_2.setFont(font)
        self.input_2.setFrameShape(QtWidgets.QFrame.Box)
        self.input_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.input_2.setLineWidth(2)
        self.input_2.setAlignment(QtCore.Qt.AlignCenter)
        self.input_2.setObjectName("input_2")
        self.input_3 = QtWidgets.QLabel(self.centralwidget)
        self.input_3.setGeometry(QtCore.QRect(20, 110, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_3.setFont(font)
        self.input_3.setFrameShape(QtWidgets.QFrame.Box)
        self.input_3.setLineWidth(2)
        self.input_3.setAlignment(QtCore.Qt.AlignCenter)
        self.input_3.setObjectName("input_3")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.delete())
        self.deleteButton.setGeometry(QtCore.QRect(490, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")
        self.input = QtWidgets.QLineEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(110, 10, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input.setFont(font)
        self.input.setInputMask("")
        self.input.setText("")
        self.input.setFrame(True)
        self.input.setObjectName("input")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(110, 110, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output.setFont(font)
        self.output.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.output.setText("")
        self.output.setScaledContents(False)
        self.output.setWordWrap(False)
        self.output.setObjectName("output")
        self.input.raise_()
        self.convertButton.raise_()
        self.input_2.raise_()
        self.input_3.raise_()
        self.deleteButton.raise_()
        self.output.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 553, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def delete(self):
        self.input.setText("")
        self.output.setText("")
        
    def convert(self):
        try:
            output = self.input.text()
            output = eval(output)
            output = str(bin(output))
            self.output.setText(output[2:])
        except:
            self.output.setText("Error")
     
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.convertButton.setText(_translate("MainWindow", "Convert"))
        self.input_2.setText(_translate("MainWindow", "Decimal"))
        self.input_3.setText(_translate("MainWindow", "Binary"))
        self.deleteButton.setText(_translate("MainWindow", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
